server:
  port: 8080
  #gizp压缩
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/easy-query-test?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 30MB # 设置单个文件大小
      max-request-size: 30MB # 设置单次请求文件的总大小

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


easy-query:
  enable: true
  database: mysql
  name-conversion: underlined
  delete-throw: true
  print-sql: true
  default-track: true
  keep-native-style: true
